CREATE TABLE  IF NOT EXISTS T_MICRO_SERVICE (
  ID NUMBER PRIMARY KEY,
  MICROSERVICENAME VARCHAR,
  MICROSERVICEALIAS VARCHAR
);
CREATE TABLE  IF NOT EXISTS T_MICRO_SERVICE_INSTANCE (
  ID NUMBER PRIMARY KEY,
  SERVICEID NUMBER,
  INSTANCEID VARCHAR,
  HOSTNAME VARCHAR,
  APP VARCHAR,
  IPADDR VARCHAR,
  PORT VARCHAR
);
CREATE TABLE  IF NOT EXISTS T_MACHINE (
  ID VARCHAR PRIMARY KEY,
  NAME VARCHAR,
  ALIAS VARCHAR,
  IP_ADDRESS VARCHAR,
  USER_NAME VARCHAR,
  PORT INT,
  OS_TYPE VARCHAR,
  STATUS INT,
  DESCRIPTION VARCHAR,
  CREATE_TIME VARCHAR,
  UPDATE_TIME VARCHAR,
  CPU VARCHAR,
  MEMORY VARCHAR,
  DISK VARCHAR,
  CPUNUM INT,
  DISKSIZE VARCHAR,
  MEMORYSIZE VARCHAR,
  BALANCE VARCHAR,
  CPUCORE VARCHAR
);
CREATE TABLE  IF NOT EXISTS T_ISSUE (
  ID VARCHAR PRIMARY KEY,
  IP_ADDRESS VARCHAR,
  ISSUETYPE VARCHAR,
  ISSUE_DESC VARCHAR,
  WARN_LEVEL VARCHAR,
  CREATE_TIME VARCHAR,
  UPDATE_TIME VARCHAR
);
CREATE TABLE  IF NOT EXISTS T_THRESHOLD (
  ID VARCHAR PRIMARY KEY,
  INDICATOR_BODY VARCHAR,
  INDICATOR_NAME VARCHAR,
  INDICATOR_SYMBOL VARCHAR,
  THRESHOLD INT,
  CREATE_TIME VARCHAR,
  UPDATE_TIME VARCHAR
);
CREATE TABLE  IF NOT EXISTS T_SCRAPE_CONFIG (
  ID VARCHAR PRIMARY KEY,
  JOB_NAME VARCHAR,
  SCHEME VARCHAR,
  SCRAPE_INTERVAL INT,
  METRICS_PATH VARCHAR,
  STATIC_CONFIGS_TARGETS VARCHAR,
  STATIC_CONFIGS_LABELS_INSTANCE VARCHAR,
  CONSUL_SD_CONFIGS_SERVER VARCHAR,
  CONSUL_SD_CONFIGS_SCHEME VARCHAR,
  CONSUL_SD_CONFIGS_SERVERNAME VARCHAR,
  CREATE_TIME VARCHAR,
  UPDATE_TIME VARCHAR
);
CREATE TABLE  IF NOT EXISTS T_RULE_FILE_CONFIG (
  ID VARCHAR PRIMARY KEY,
  GROUPS_NAME VARCHAR,
  NAME VARCHAR,
  EXPR VARCHAR,
  FORTIME VARCHAR,
  LABELS_SEVERITY VARCHAR,
  ANNOTATIONS_SUMMARY VARCHAR,
  ANNOTATIONS_DESCRIPTION VARCHAR,
  CREATE_TIME VARCHAR,
  UPDATE_TIME VARCHAR
);
