CREATE TABLE  IF NOT EXISTS T_MICRO_SERVICE (
  ID NUMBER PRIMARY KEY,
  MICROSERVICENAME VARCHAR,
  MICROSERVICEALIAS VARCHAR,
  INSTANCEID VARCHAR,
  HOSTNAME VARCHAR,
  APP VARCHAR,
  IPADDR VARCHAR
);